---
title: "TOY_1"
author: "Paula Moreno Blazquez"
date: "Enero 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r PAQUETES}
library(tidyr)
library(dplyr)
```



# PARTE 1: Crear Stints

## DATA

```{r}
homeplayer <- paste0("homeplayer",1:10)
awayplayer <- paste0("awayplayer",1:10)


toy <- data.frame(
  "id_play" = 1:15,
  "season" = c(rep("S2017",15)),
  "game_code_code" = c(rep("G1",10), rep("G2",5)),
  "quarter" = c(rep(1,3), rep(2,2),rep(3,2),rep(4,3),rep(1,4),rep(2,1)),
  "minute" = c(0,3,5,11,15,21,27,31,33,36,0,3,4,6,11),
  "points_home" =    c(0,0,0,2,2,2,5,5,7,7,0,3,3,5,6),
  "points_away" = c(0,2,2,2,4,4,7,7,9,9,0,0,2,2,2),
  "homeplayer1" = c(rep(homeplayer[1],4),rep(homeplayer[6],5),rep(homeplayer[1],6)),
  "homeplayer2" = homeplayer[2],
  "homeplayer3" = c(rep(homeplayer[3],7), rep(homeplayer[7],2),rep(homeplayer[3],6)),
  "awayplayer1" = awayplayer[1],
  "awayplayer2" = c(rep(awayplayer[2],8),awayplayer[7], rep(awayplayer[2],6)),
  "awayplayer3" = awayplayer[3]
  )

toy2 <- data.frame(                         #DF2 para comprovar que funciona
  "id_play" = 1:20,
  "season" = c(rep("S2017",20)),
  "game_code" = c(rep("G1",10), rep("G2",10)),
  "quarter" = c(rep(1,3), rep(2,2),rep(3,2),rep(4,3),rep(1,4),rep(2,6)),
  "minute" = c(0,3,5,11,15,21,27,31,33,36,0,3,4,6,11,12,14,16,17,19),
  "points_home" = c(0,0,0,2,2,2,5,5,7,7,0,2,2,5,5,7,7,7,9,10),
  "points_away" = c(0,2,2,2,4,4,7,7,9,9,0,0,2,2,4,4,6,6,6,6),
  "homeplayer1" = c(rep(homeplayer[1],4),rep(homeplayer[6],5),rep(homeplayer[1],8), rep(homeplayer[1],3)),
  "homeplayer2" = homeplayer[2],
  "homeplayer3" = c(rep(homeplayer[3],7), rep(homeplayer[7],2),rep(homeplayer[3],9), rep(homeplayer[9],2)),
  "awayplayer1" = awayplayer[1],
  "awayplayer2" = c(rep(awayplayer[2],8),awayplayer[7], rep(awayplayer[2],9), rep(awayplayer[5],2)),
  "awayplayer3" = awayplayer[3]
  )


toy_backup <- toy

df <- toy2

df <- df %>% unite("lineups", homeplayer1:awayplayer3, remove = TRUE)

names(df)
df

```

## MERGE Temporada+game_code

```{r}
df_merged <- df %>%  unite("SeasonGame", c("season", "game_code"))
df_merged
```


## ORDENAR DF -> Ya no hace falta

```{r eval=FALSE, include=FALSE}
players_pbp <- df %>% select(matches("_player[1-5]")) #subset de solo jugadores pbp
resto_pbp <- df %>% select(!matches("_player[1-5]"))

## Ordenar alfabeticamente jugadores
order_players_pbp <- lapply(1:nrow(players_pbp), function(row) 
                     players_pbp[row, order(players_pbp[row, ], decreasing = TRUE)])
df_order_players_pbp <- data.frame(matrix(unlist(order_players_pbp), 
                        nrow=length(order_players_pbp), byrow=TRUE))
names(df_order_players_pbp) <- names(players_pbp)

df <- cbind(resto_pbp, df_order_players_pbp)

df
```



## UNIQUE quintetos

```{r}
library(dplyr)

# Columnas TRUE o FALSE si son iguales a su lag row
df_merged$players_SAME <- df_merged$lineups == lag(df_merged$lineups)
df_merged$SeasonGame_SAME <- df_merged$SeasonGame == lag(df_merged$SeasonGame)

## Determinamos los primeros elementos de estas dos variables como FALSE para que no  
## nos aparezca NA, ya que no puede evaluar con anterior
df_merged$players_SAME[1]    <- FALSE
df_merged$SeasonGame_SAME[1] <- FALSE

df_merged$NEW_STINT <- ifelse(((df_merged$players_SAME == FALSE)|(df_merged$SeasonGame_SAME == FALSE )), 
                              TRUE, FALSE)
        ### 1ra condicions para cambio de jugadores y 2nda para cambio de partido.

df_merged
```

Hasta aquí tenemos detectados cuando hay cambios

## STINTS

```{r}
### Filas que tenemos que conservar:
df_merged$stint <- ifelse((lead(df_merged$NEW_STINT) == TRUE)|(df_merged$SeasonGame_SAME == FALSE ), 
                          df_merged$NEW_STINT, NA)     
### La primera condicion nos mantiene las que son iguales anterior a la fila en la que estamos
### ha habiado cambio. La segunda condicion nos mantiene la primera entrada de cada partido.



# Para que nos aparezcan tambien la primera y la ultima entrada:
n_df <- dim(df_merged)[1]
df_merged$stint[1] <- df_merged$NEW_STINT[1]
df_merged$stint[n_df] <- df_merged$NEW_STINT[n_df]

df_merged

STINTS <- df_merged %>% drop_na(stint)         #Eliminar NA rows
STINTS$ID_Stint <- 1:nrow(STINTS)              #Crear Identificador Stints

STINTS$stint_minutes <- ifelse(STINTS$SeasonGame_SAME == TRUE, STINTS$minute - lag(STINTS$minute), 0)

#View(STINTS %>% select(c(ID_Stint, stint_minutes, points_home, points_away)))

PM_function <- function(h,a){
  PM <- (h-lag(h))-(a-lag(a))
  PM
}

STINTS$PM_H <- ifelse(STINTS$SeasonGame_SAME == TRUE, 
                      PM_function(STINTS$points_home, STINTS$points_away), 0)

STINTS$PM_A <- -STINTS$PM_H
STINTS

STINTS_Reduced <- STINTS %>% select(c(lineups, stint_minutes, PM_H, PM_A))
STINTS_Reduced

# Sumar PM de los mismos lineups:
STINTS_Reduced_Lineups <-  aggregate(. ~ lineups, STINTS_Reduced, sum, na.rm = TRUE)
STINTS_Reduced_Lineups
```



# PARTE 2:  Dummys Jugadores

```{r eval=FALSE, include=FALSE}
#PRUEBA1

vec_players <- unique(c(homeplayer, awayplayer))             #Vector con los nombres de los jugadores
#length(vec_players)

NA_players <- matrix(data=NA, nrow = dim(STINTS_PM)[1], ncol = length(vec_players)) #Solo jugadores

df_DummyPlayers <- cbind(STINTS_PM, NA_players)                     #DF con jugadores como columnas
names(df_DummyPlayers) <- c(names(STINTS_PM), vec_players)

## TRUE/FALSE si aparecen en la alineacion
df_DummyPlayers[vec_players] <- grepl(vec_players, df_DummyPlayers$lineups, fixed=TRUE) 

#Me las rellena todas igual al primer jugador que aparece en vec_players (homeplayer1). Como hacer 
#para que rellene con todos los jugadores??


#Como deberian ser:
d1 <- grepl(vec_players[1], df_DummyPlayers$lineups, fixed=TRUE) #homeplayer1
d2 <- grepl(vec_players[2], df_DummyPlayers$lineups, fixed=TRUE) #homeplayer2
d3 <- grepl(vec_players[3], df_DummyPlayers$lineups, fixed=TRUE) #homeplayer3
d4 <- grepl(vec_players[4], df_DummyPlayers$lineups, fixed=TRUE) #homeplayer4

df_Dum <- data.frame(
  "homeplayer1" <- d1,
  "homeplayer2" <- d2,
  "homeplayer3" <- d3,
  "homeplayer4" <- d4
)

names(df_Dum) <- paste0("homeplayer", 1:4)
df_Dum

#Lo que sale
df_DummyPlayers
```

```{r}
#PRUEBA2 - fastDummies

# Vector con todos los nombres de los jugadores:
vec_players <- unique(c(homeplayer, awayplayer)) 
length(vec_players)

## DUDA:
# Como especifico que jugador tiene PM positivo o negativo? Dependiendo de si local o visitante, 
# su PM sera diferente, pero no siempre sera LOCAL. Como determino de cual es cual?

df_dummys <- fastDummies::dummy_cols(STINTS_Reduced_Lineups, select_columns = "lineups", split = "_")
df_dummys_sort <- df_dummys[ , order(names(df_dummys))]

df_dummys_sort[-1]
```



